var Ardublockly = Ardublockly || {};
Ardublockly.LOCALISED_TEXT = {
  translationLanguage: "English",
  title: "Flag's Block",
  blocks: "Blocks",
  projectName: "Untitled Project",
  projectFileType: "Project File",
  /* Menu */
  undo: "Undo",
  redo: "Redo",
  new: "New",
  open: "Open",
  save: "Save",
  saveas: "Save As",
  deleteAll: "Delete All",
  settings: "Settings",
  installDriver: "Install Driver",
  // added by Mee
  driverFlagsOne: "Flag's ONE",
  driverFlags1: "Flag's 1",
  driverD1Mini: "D1 mini",
  uploadSound: "Upload Sound",
  uploadHTML: "Upload Web Page",
  // ------------  
  about: "About",
  documentation: "Documentation",
  reportBug: "Report Bug",
  examples: "Examples",
  layout: "Layout",
  horizontal: "Horizontal",
  vertical: "Vertical",
  /* Settings */
  compilerLocation: "Compiler Location",
  compilerLocationDefault: "Compiler Location unknown",
  sketchFolder: "Sketch Folder",
  sketchFolderDefault: "Sketch Folder unknown",
  arduinoBoard: "Arduino Board",
  arduinoBoardDefault: "Arduino Board unknown",
  comPort: "COM Port",
  comPortDefault: "COM Port unknown",
  defaultIdeButton: "Default IDE Button",
  defaultIdeButtonDefault: "IDE options unknown",
  language: "Language",
  languageDefault: "Language unknown",
  sketchName: "Sketch Name",
  /* Arduino console output */
  arduinoOpMainTitle: "Arduino IDE output",
  arduinoOpWaiting: "Waiting for the IDE output...",
  arduinoOpUploadedTitle: "Successfully Uploaded Sketch",
  arduinoOpVerifiedTitle: "Successfully Verified Sketch",
  arduinoOpOpenedTitle: "Sketch opened in IDE",
  arduinoOpOpenedBody: "The sketch should be loaded in the Arduino IDE.",
  arduinoOpErrorUpVerTitle: "Build or Upload failed",
  arduinoOpErrorSketchTitle: "Sketch not found",
  arduinoOpErrorFlagTitle: "Invalid command line argument",
  arduinoOpErrorFlagPrefTitle: "Preference passed to 'get-pref' flag does not exist",
  arduinoOpErrorIdeDirTitle: "Unable to find Arduino IDE",
  arduinoOpErrorIdeDirBody: "The compiler directory has not been set.<br>" +
                            "Please set it in the Settings.",
  arduinoOpErrorIdeOptionTitle: "What should we do with the Sketch?",
  arduinoOpErrorIdeOptionBody: "The launch IDE option has not been set.<br>" +
                               "Please select an IDE option in the Settings.",
  arduinoOpErrorIdePortTitle: "Serial Port unavailable",
  arduinoOpErrorIdePortBody: "The Serial Port is not accessible.<br>" +
                             "Please check if the Arduino is correctly connected to the PC and select the Serial Port in the Settings.",
  arduinoOpErrorIdeBoardTitle: "Unknown Arduino Board",
  arduinoOpErrorIdeBoardBody: "The Arduino Board has not been set.<br>" +
                              "Please select the appropriate Arduino Board from the settings.",
  /* Modals */
  noServerTitle: "An error occurred",
  noServerBody: "Sorry that Flag's Block does not work properly for some reason. Please submit a false positive report by sending an email to <a href='mailto:FlagService<service@flag.com.tw>'>service@flag.com.tw</a>",
  noServerNoLangBody: "If the Flag's Block application is not running the language cannot be fully changed.",
  addBlocksTitle: "Additional Blocks",
  /* Alerts */
  loadNewBlocksTitle: "Load new blocks?",
  loadNewBlocksBody: "Loading a new XML file will replace the current blocks from the workspace.<br><br>" +
                     "Are you sure you want to proceed?",
  discardBlocksTitle: "Delete blocks?",
  discardBlocksBody: "There are %1 blocks on the workspace.<br>" +
                     "Are you sure you want to delete them?",
  invalidXmlTitle: "Invalid XML",
  invalidXmlBody: "The XML file was not successfully parsed into blocks. Please review the XML code and try again.",
  invalidNameTitle: "Invalid Name",
  invalidNameBody: "The name that you typed is already in use. Please type a different name.", 
  driverNotSupportedTitle: "This OS is not supported",
  driverNotSupportedBody: "The driver is only supported on Windows, please download Arduino Software from <a href='https://www.arduino.cc' target='_blank'>https://www.arduino.cc</a>.",
  emptyValue : "You need to write something.",
  changesNotSaved: "You have made changes. If you navigate away you will loose your unsaved changes. Are you sure you want to exit?",
  changesNotSavedTitle: "Save changes?",
  changesNotSavedBody: "You have made changes. Do you want to save these changes?<br><br>" + 
                       "If you hit 'NO', all unsaved changes will be lost!",
  changeLanguageReloadTitle: "Reload Application?",
  changeLanguageReloadBody: "Changing Language will reload whole application. All unsaved changes will be lost.<br><br>" +
                            "Are you sure you want to proceed?",
  firstRunTitle: "Please set serial port",
  firstRunBody: "Looks like that you are executing this software for the first time or just updated version. Please set the serial port used by Arduino to upload the program to Arduino.",
  aboutTitle: "About Flag's Block",
  aboutBody: "Flag's Block is a visual block programming language provided by <a href='http://www.flag.com.tw/' target='_blank'>Flag Technology Co.,Ltd.</a>, It allows users to drag-and-drop visual blocks to create an Arduino programs. <br /><br />Flag's Block is licensed under the <a href='http://www.gnu.org/licenses/gpl-3.0.html' target='_blank'>GUN GPL 3.0</a>, and is developed on the basis of the following software: <ul><li><a href='https://developers.google.com/blockly/' target='_blank'>Google Blockly</a></li><li><a href='http://ardublockly.embeddedlog.com/' target='_blank'>ArduBlockly</a></li></ul>",
  /* Tooltips */
  uploadingSketch: "Uploading Sketch into Arduino...",
  uploadSketch: "Upload Sketch to the Arduino",
  verifyingSketch: "Verifying Sketch...",
  verifySketch: "Verify the Sketch",
  openingSketch: "Opening Sketch in the Arduino IDE...",
  openSketch: "Open Sketch in IDE",
  notImplemented: "Function not yet implemented",
  projectSaving: "Saving project...",
  projectOpening: "Opening project...",
  projectNotChanged: "The project is not changed",
  projectSaved: "The project has been saved",
  projectSaveFailed: "Failed to save the project, error code:%1 ",
  exampleNotAvaileableInThisLang: "Sorry, this example has not been translated into %1",
  //added by Mee
  soundUploaded: "The sound data has been uploaded",
  soundUploadFailed: "Failed to upload the sound data, error code：%1 ",
  HTMLUploaded: "The HTML data has been uploaded",
  HTMLUploadFailed: "Failed to upload the HTML data, error code：%1 ",
  //------------
  /* Prompts */
  ok: "OK",
  yes: "Yes",
  no: "No",
  okay: "Okay",
  cancel: "Cancel",
  return: "Return",
  inputProjectName: "Please Input Project Name",
  /* Cards */
  arduinoSourceCode: "Arduino Source Code",
  blocksXml: "Blocks XML",
  /* Toolbox Categories*/
  catLogic: "Logic",
  catLoops: "Loops",
  catMath: "Math",
  catText: "Text",
  catData: "Data format",
  catArray: "Array",
  catVariables: "Variables",
  catFunctions: "Functions",
  catInputOutput: "Input/Output",
  catInput: "Input",
  catOutput: "Output",
  catTime: "Time",
  catAudio: "Audio",
  catMotors: "Motors",
  catComms: "Comms",
  catSerial: "Serial",
  // added by MEE
  catSoftwareSerial: "Software Serial",
  catESP8266: "ESP8266 WiFi",
  catESP8266IOT: "ESP8266 IOT",
  catFlagLedStripe: "LED Stripe",
  catI2CLCD: "I2C LCD",
  catTM1637: "TM1637 4 digit",
  catSensors: "Sensors",
  catSound: "Sound",
  catDanceRobot: 'Dance Robot',
  // -----------------
  catMisc: "Misc",
  // added by SAM
  catAI: "AI",
  // -----------------

  /* Examples */
  examples_F6789A: "F6789A",
  examples_F6789A_1_1: "LAB 1-1 Blinking a LED",
  examples_F6789A_3_1: "LAB 3-1 Digital output - external LED",
  examples_F6789A_3_2: "LAB 3-2 Digital input - button",
  examples_F6789A_4_1: "LAB 4-1 Analog output - PWM",
  examples_F6789A_4_2: "LAB 4-2 Analog input - variable resistance",
  examples_F6789A_5: "LAB 5 Serial port",
  examples_F6789A_6: "LAB 6 Tri-color RGB LED",
  examples_F6789A_7_1: "LAB 7-1 Knight Rider LED scanner",
  examples_F6789A_7_2: "LAB 7-2 Adjust scanner speed",
  examples_F6789A_8: "LAB 8 Light sensor",
  examples_F6789A_9_1: "LAB 9-1 Temperature sensor",
  examples_F6789A_9_2: "LAB 9-2 Temperature alarm",
  examples_F6789A_10: "LAB 10 Wet sensor",
  examples_F6789A_11: "LAB 11 Seven-segment display",

  examples_FM601A: "FM601A",
  examples_FM602A: "FM602A",
  examples_FM603A: "FM603A",
  examples_FM604A: "FM604A",
  examples_FM605A: "FM605A",

  examples_FM607A: "The Self-Driving Car",
  examples_FM607_04: "LAB 04 Move forward or backward",
  examples_FM607_05: "LAB 05 Control the speed",
  examples_FM607_06: "LAB 06 Control the direction",
  examples_FM607_07: "LAB 07 Illumination test",
  examples_FM607_08: "LAB 08 Use a ﬂashlight to control the Car",
  examples_FM607_09: "LAB 09 Build the website for controlling Car",
  examples_FM607_10: "LAB 10 Upload the pre-installed program",
};
