var Ardublockly = Ardublockly || {};
Ardublockly.LOCALISED_TEXT = {
  translationLanguage: "繁體中文",
  title: "Flag's Block",
  blocks: "積木",
  projectName: "未命名專案",
  projectFileType: "Flag's Block 專案檔",
  /* Menu */
  undo: "上一步",
  redo: "下一步",
  new: "新專案",
  open: "開啟",
  save: "儲存",
  saveas: "另存新專案",
  uploadsound: "上傳音樂資料",
  uploadHTML: "上傳網頁資料",
  deleteAll: "全部刪除",
  settings: "設定",
  installDriver: "安裝驅動程式",
  // added by Mee
  driverFlagsOne: "Flag's ONE",
  driverFlags1: "Flag's 1",
  driverD1Mini: "D1 mini",
  uploadSound: "上傳音樂資料",
  uploadHTML: "上傳網頁資料",
  // ------------
  about: "關於",
  documentation: "文件",
  reportBug: "回報 Bug",
  examples: "範例",
  layout: "版面配置",
  horizontal: "水平",
  vertical: "垂直",
  /* Settings */
  compilerLocation: "Arduino 執行檔位置",
  compilerLocationDefault: "尚未設定 Arduino 執行檔位置",
  sketchFolder: "草稿碼資料夾",
  sketchFolderDefault: "尚未設定草稿碼資料夾",
  arduinoBoard: "Arduino 開發板型號",
  arduinoBoardDefault: "尚未設定 Arduino 開發板型號",
  comPort: "序列埠",
  comPortDefault: "尚未設定序列埠編號",
  defaultIdeButton: "IDE 按鈕預設動作",
  defaultIdeButtonDefault: "尚未設定 IDE 按鈕預設動作",
  language: "語系 (Language)",
  languageDefault: "尚未設定語系",
  sketchName: "草稿碼名稱",
  /* Arduino console output */
  arduinoOpMainTitle: "Arduino IDE 執行結果",
  arduinoOpWaiting: "正在等待 Arduino IDE 輸出的資訊...",
  arduinoOpUploadedTitle: "已經成功將草稿碼上傳到 Arduino 板執行",
  arduinoOpVerifiedTitle: "草稿碼的程式檢查成功",
  arduinoOpOpenedTitle: "已經成功在 Arduino IDE 中開啟草稿碼",
  arduinoOpOpenedBody: "草稿碼已經開啟, 您可以使用 Arduino IDE 編輯與上傳程式",
  arduinoOpErrorUpVerTitle: "編譯或上傳時發生錯誤",
  arduinoOpErrorSketchTitle: "找不到草稿碼",
  arduinoOpErrorFlagTitle: "命令列參數錯誤",
  arduinoOpErrorFlagPrefTitle: "Preference passed to 'get-pref' flag does not exist",
  arduinoOpErrorIdeDirTitle: "找不到 Arduino IDE",
  arduinoOpErrorIdeDirBody: "Arduino 執行檔位置尚未設定<br>" +
                            "請檢查或重設相關設定.",
  arduinoOpErrorIdeOptionTitle: "What should we do with the Sketch?",
  arduinoOpErrorIdeOptionBody: "The launch IDE option has not been set.<br>" +
                               "Please select an IDE option in the Settings.",
  arduinoOpErrorIdePortTitle: "序列通訊埠無法連線",
  arduinoOpErrorIdePortBody: "無法透過序列埠連線 Arduino.<br>" +
                             "請檢查設定內的序列埠是否正確, 或者檢查 Arduino 是否連接電腦的 USB.",
  arduinoOpErrorIdeBoardTitle: "Unknown Arduino Board",
  arduinoOpErrorIdeBoardBody: "The Arduino Board has not been set.<br>" +
                              "Please select the appropriate Arduino Board from the settings.",
  /* Modals */
  noServerTitle: "發生錯誤",
  noServerBody: "抱歉 Flag's Block 發生異常錯誤. 請透過 e-mail <a href='mailto:FlagService<service@flag.com.tw>'>service@flag.com.tw</a> 將這個錯誤回報給我們",
  noServerNoLangBody: "If the Flag's Block application is not running the language cannot be fully changed.",
  addBlocksTitle: "Additional Blocks",
  /* Alerts */
  loadNewBlocksTitle: "是否要開啟專案?",
  loadNewBlocksBody: "開啟其他專案將刪除目前所有積木, 請記得存檔否則您的專案將會遺失!<br><br>" +
                     "確定要開啟專案嗎?",
  discardBlocksTitle: "是否要刪除積木?",
  discardBlocksBody: "目前尚有 %1 個積木在工作區.<br>" +
                     "您確定要刪除所有積木嗎?",
  invalidXmlTitle: "專案檔內的 XML 格式錯誤",
  invalidXmlBody: "專案檔內的 XML 無法成功轉換為積木, 請檢查 XML 的語法後再試一次.",
  invalidNameTitle: "名稱錯誤",
  invalidNameBody: "您輸入的變數名稱已經使用過了或者不合格式, 請重新輸入不同的名稱.",
  driverNotSupportedTitle: "作業系統不支援",
  driverNotSupportedBody: "本程式內建的驅動程式只支援 Windows 系統, 請您自行到 <a href='https://www.arduino.cc' target='_blank'>https://www.arduino.cc</a> 下載 Arduino Software.",
  emptyValue : "您尚未輸入任何資料.",
  changesNotSaved: "修改過的內容尚未儲存, 請問確定要離開嗎?",
  changesNotSavedTitle: "是否儲存?",
  changesNotSavedBody: "您的專案已經修改過了, 是否要儲存這些變更?<br><br>" +
                       "請小心, 若按 [否] 您將遺失所有修改過的內容!",
  changeLanguageReloadTitle: "是否要重新啟動?",
  changeLanguageReloadBody: "切換語言需要重新啟動本程式, 請先存檔否則您的專案將會遺失!<br><br>" +
                     "確定要重新啟動嗎?",
  firstRunTitle: "請設定序列埠",
  firstRunBody: "您似乎是第一次執行本軟體或者剛剛更新版本, 請設定 Arduino 使用的序列埠號, 才能將程式上傳到 Arduino 執行.",
  aboutTitle: "關於 Flag's Block",
  aboutBody: "Flag's Block 為<a href='http://www.flag.com.tw/' target='_blank'>旗標科技股份有限公司</a>研發之圖形程式開發環境, 可用來設計 Arduino 程式.<br /><br />本產品採用 <a href='http://www.gnu.org/licenses/gpl-3.0.html' target='_blank'>GUN GPL 3.0 授權</a>, 是在以下軟體的基礎上所開發完成: <ul><li><a href='https://developers.google.com/blockly/' target='_blank'>Google Blockly</a></li><li><a href='http://ardublockly.embeddedlog.com/' target='_blank'>ArduBlockly</a></li></ul>",
  /* Tooltips */
  uploadingSketch: "正在將草稿碼上傳到 Arduino 板執行...",
  uploadSketch: "將草稿碼上傳到 Arduino 板執行",
  verifyingSketch: "正在檢查草稿碼...",
  verifySketch: "檢查草稿碼的程式是否正確",
  openingSketch: "正準備在 Arduino IDE 中開啟程式碼...",
  openSketch: "在 Arduino IDE 中開啟程式碼",
  notImplemented: "本功能尚未實作",
  projectSaving: "正在儲存專案...",
  projectOpening: "正在開啟專案...",
  projectNotChanged: "專案尚未修改",
  projectSaved: "專案已經儲存完畢",
  projectSaveFailed: "專案儲存失敗, 錯誤碼：%1 ",
  exampleNotAvaileableInThisLang: "抱歉, 此範例尚未翻譯為 %1",
  //added by Mee
  soundUploaded: "聲音資料已上傳",
  soundUploadFailed: "聲音資料上傳失敗, 錯誤碼：%1 ",
  HTMLUploaded: "網頁資料已上傳",
  HTMLUploadFailed: "網頁資料上傳失敗, 錯誤碼：%1 ",
  //------------
  /* Prompts */
  ok: "是",
  yes: "是",
  no: "否",
  okay: "確定",
  cancel: "取消",
  return: "返回",
  inputProjectName: "請輸入專案名稱",
  /* Cards */
  arduinoSourceCode: "Arduino 程式草稿碼",
  blocksXml: "Blocks XML",
  /* Toolbox Categories*/
  catLogic: "邏輯",
  catLoops: "流程控制",
  catMath: "數學",
  catText: "文字",
  catData: "資料格式",
  catArray: "陣列",
  catVariables: "變數",
  catFunctions: "函式",
  catInputOutput: "輸入/輸出",
  catInput: "腳位輸入",
  catOutput: "腳位輸出",
  catTime: "時間",
  catAudio: "聲音",
  catMotors: "馬達",
  catComms: "通訊",
  catSerial: "序列通訊",
  // added by MEE
  catSoftwareSerial: "軟體序列埠",
  catESP8266: "ESP8266 無線網路",
  catESP8266IOT: "ESP8266 物聯網",
  catFlagLedStripe: "條燈與環燈",
  catI2CLCD: "I2C LCD 液晶顯示器",
  catTM1637: "TM1637 4 位數顯示器",
  catSensors: "感測器",
  catSound: "音效",
  catDanceRobot: '跳舞機器人',
  // -----------------
  catMisc: "其他",
  // added by SAM
  catAI: "人工智慧",
  // -----------------
};
